name: API Build and Deploy

on:
  push:
    branches: [ "master" ]
    paths:
      - 'api/**'

jobs:

  api-build-and-deploy:
    name: API Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REGISTRY }}

    - name: Build the Docker image
      run: |
        docker build -f ./api/Dockerfile ./api -t ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest

    - name: Redeploy Lightsail with latest image
      run: |
        CONTAINERS=$(aws lightsail get-container-service-deployments --service-name "blu-presenter-api" --query 'deployments[0].containers' --output json)
        aws lightsail create-container-service-deployment --service-name "blu-presenter-api" --containers "$CONTAINERS"
